---
schema:
  procedures: {}
  tables:
    video:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - video_id
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
        - deferrable: 1
          expression: ''
          fields:
            - yt_id
          match_type: ''
          name: video_yt_id
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: UNIQUE
      fields:
        video_id:
          data_type: integer
          default_value: ~
          is_auto_increment: 1
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: video_id
          order: 1
          size:
            - 0
        yt_id:
          data_type: text
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 1
          name: yt_id
          order: 2
          size:
            - 0
      indices: []
      name: video
      options: []
      order: 1
  triggers: {}
  views: {}
translator:
  add_drop_table: 0
  filename: ~
  no_comments: 0
  parser_args:
    package: &1 !!perl/hash:Web::Scenefinity::Schema
      class_mappings:
        DBIx::Class::DeploymentHandler::VersionStorage::Standard::VersionResult: __VERSION
        Web::Scenefinity::Schema::Result::Video: Video
      source_registrations:
        Video: !!perl/hash:DBIx::Class::ResultSource::Table
          _columns:
            video_id:
              data_type: integer
              is_auto_increment: 1
            yt_id:
              data_type: text
          _columns_info_loaded: 0
          _ordered_columns:
            - video_id
            - yt_id
          _primaries: &2
            - video_id
          _relationships: {}
          _unique_constraints:
            primary: *2
            video_yt_id:
              - yt_id
          name: video
          result_class: Web::Scenefinity::Schema::Result::Video
          resultset_attributes: {}
          resultset_class: Web::Scenefinity::Schema::ResultSet::Video
          schema: *1
          source_name: Video
        __VERSION: !!perl/hash:DBIx::Class::ResultSource::Table
          _columns:
            ddl:
              data_type: text
              is_nullable: 1
            id:
              data_type: int
              is_auto_increment: 1
            upgrade_sql:
              data_type: text
              is_nullable: 1
            version:
              data_type: varchar
              size: 50
          _columns_info_loaded: 0
          _ordered_columns:
            - id
            - version
            - ddl
            - upgrade_sql
          _primaries: &3
            - id
          _relationships: {}
          _unique_constraints:
            dbix_class_deploymenthandler_versions_version:
              - version
            primary: *3
          name: dbix_class_deploymenthandler_versions
          result_class: DBIx::Class::DeploymentHandler::VersionStorage::Standard::VersionResult
          resultset_attributes: {}
          resultset_class: DBIx::Class::DeploymentHandler::VersionStorage::Standard::VersionResultSet
          schema: *1
          source_name: __VERSION
      storage: !!perl/hash:DBIx::Class::Storage::DBI
        _connect_info:
          - ~
        _dbh_details: {}
        _dbh_gen: 0
        _dbi_connect_info:
          - ~
          - ~
          - ~
          - &4
            AutoCommit: 1
            PrintError: 0
            RaiseError: 1
            ShowErrorStatement: 1
        _dbic_connect_attributes: *4
        _in_do_block: 0
        _sql_maker: ~
        _sql_maker_opts: {}
        savepoints: []
        schema: *1
        transaction_depth: 0
    sources:
      - Video
  parser_type: SQL::Translator::Parser::DBIx::Class
  producer_args: {}
  producer_type: SQL::Translator::Producer::YAML
  show_warnings: 0
  trace: 0
  version: 0.11011
